// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
import { resolve } from 'path';
import { defineConfig } from 'prisma/config';

dotenv.config({ path: resolve(process.cwd(), '.env') });

const databaseUrl = process.env.DATABASE_URL;

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasource: {
    url: databaseUrl,
  },
  migrations: {
    seed: 'ts-node ./prisma/seed.ts',
  },
});
